apiVersion: apps/v1
kind: Deployment
metadata:
  name: juse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juse
  template:
    metadata:
      labels:
        app: juse
    spec:
      containers:
      - image: okteto.dev/juse:latest
        name: juse
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "49f2851a-7564-48c0-91a1-c87cae4b6df7"
        - name: Vless_Path
          value: "/235rer"
        - name: Vmess_UUID
          value: "49f2851a-7564-48c0-91a1-c87cae4b6df7"
        - name: Vmess_Path
          value: "/23efw"
        - name: Share_Path
          value: "/share233"
